new assert

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -76,10 +76,13 @@ jobs:
         run: |
           echo "Assertion failed for TARGET_ENVIRONMENT: $TARGET_ENVIRONMENT != PROD"
           exit 1  
-      - if: ${{ secrets.TESTSECRET != 'HELLO_WORLD' }}
-        run: |
-          echo "Assertion failed for TESTSECRET: TESTSECRET_PROD != HELLO_WORLD"
-          exit 1
+      - run: |
+          if [ ${{ secrets.TESTSECRET }} != "HELLO_WORLD" }} ]; then
+            echo "❌ Assertion failed for TESTSECRET: TESTSECRET_PROD != HELLO_WORLD"
+            exit 1
+          else 
+            echo "✅ Secrets injected"
+          fi
       - if: ${{ env.TESTENVVAR != 'Hello World' }}
         run: |
           echo "Assertion failed for TESTENVVAR: TESTENVVAR_PROD != Hello World"
